version: '3.5'

services:
  db:
    image: mongo:4.2
    container_name: db
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    image: senior-proj-backend
    container_name: senior-proj-backend
    depends_on:
      - db
    networks:
      - backend
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      NETPIE_APPID:
      NETPIE_KEY:
      NETPIE_SECRET:
      IOT_CRON:

networks:
  backend:
    name: senior-proj-backend
    driver: bridge
