version: '3.5'

services:
  db:
    volumes:
      - ./volumes/db:/data/db
    ports:
      - 27017:27017

  backend:
    image: node:8
    container_name: senior-proj-backend-dev
    volumes:
      - ./node_modules:/app/node_modules
      - ./packages/nest:/app/packages/nest
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
    ports:
      - 3000:3000
    working_dir: /app/packages/nest
    command: 'yarn start:dev'
